In [47]:
from google.colab import drive
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import io
import requests

# Mount Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. Initial Climate Variables

In [2]:
# Defining the correct folder path
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Average_Temperature"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)

            # Reading the file while skipping the first 4 lines
            df = pd.read_csv(file_path, skiprows=4)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Average Temperature')[0]

            # Modifying the Date column to extract the Year
            df['Year'] = df['Date'].astype(str).str[:4].astype(int)

            # Dropping the 'Date' column
            df.drop(columns=['Date'], inplace=True)

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Average Temperature (Units Degrees Fahrenheit)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Dropping the 'Anomaly' column
            df.drop(columns=['Anomaly'], inplace=True)

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Average Temperature (Units Degrees Fahrenheit)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Average_Temperature_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Average_Temperature.csv"
Average_Temperature_df.to_csv(output_path, index=False)

Average_Temperature_df

,State,Year,January-December Average Temperature (Units Degrees Fahrenheit)
0,Alabama,1974,63.1
1,Alabama,1975,62.8
2,Alabama,1976,60.7
3,Alabama,1977,62.5
4,Alabama,1978,61.9
...,...,...,...
2445,Wyoming,2019,40.3
2446,Wyoming,2020,42.8
2447,Wyoming,2021,43.6
2448,Wyoming,2022,42.0
2449,Wyoming,2023,42.0

In [4]:
# Defining the correct folder path for Cooling Degree Days
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 3 lines (header)
            df = pd.read_csv(file_path, skiprows=3)

            # Print columns to check structure
            print("Columns in DataFrame:")
            print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Cooling Degree Days')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Cooling Degree Days (Units Fahrenheit Degree-Days)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Cooling Degree Days (Units Fahrenheit Degree-Days)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Cooling_Degree_Days_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Cooling_Degree_Days.csv"
Cooling_Degree_Days_df.to_csv(output_path, index=False)

Cooling_Degree_Days_df

Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-2.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-3.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-4.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-5.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-6.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-7.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-8.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-9.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-10.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-11.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-12.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-13.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-14.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-15.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-16.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-17.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-18.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-19.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-20.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-21.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-22.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-23.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-24.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-25.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-26.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-27.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-28.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-29.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-30.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-31.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-32.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-33.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-34.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-35.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-36.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-37.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-38.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-39.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-40.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-41.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-42.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-43.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-44.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-45.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-46.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-47.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')
Processing file: /content/drive/My Drive/GoodNotes/Climate_Data/Cooling Degree Days/data-48.csv
Columns in DataFrame:
Index(['Date', 'Value'], dtype='object')

,State,Year,January-December Cooling Degree Days (Units Fahrenheit Degree-Days)
0,Alabama,1974,1594
1,Alabama,1975,1659
2,Alabama,1976,1424
3,Alabama,1977,2020
4,Alabama,1978,1935
...,...,...,...
2395,Wyoming,2019,246
2396,Wyoming,2020,356
2397,Wyoming,2021,413
2398,Wyoming,2022,393
2399,Wyoming,2023,254

In [5]:
# Defining the correct folder path for Heating Degree Days
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Heating Degree Days"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 3 lines (header)
            df = pd.read_csv(file_path, skiprows=3)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Heating Degree Days')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Heating Degree Days (Units Fahrenheit Degree-Days)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Heating Degree Days (Units Fahrenheit Degree-Days)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Heating_Degree_Days_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Heating_Degree_Days.csv"
Heating_Degree_Days_df.to_csv(output_path, index=False)

Heating_Degree_Days_df

,State,Year,January-December Heating Degree Days (Units Fahrenheit Degree-Days)
0,Alabama,1974,2517
1,Alabama,1975,2687
2,Alabama,1976,3275
3,Alabama,1977,3161
4,Alabama,1978,3317
...,...,...,...
2395,Wyoming,2019,8906
2396,Wyoming,2020,8069
2397,Wyoming,2021,7865
2398,Wyoming,2022,8441
2399,Wyoming,2023,8247

In [6]:
# Defining the correct folder path for Maximum Temperature
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Maximum Temperature"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 3 lines (header)
            df = pd.read_csv(file_path, skiprows=3)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Maximum Temperature')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Maximum Temperature (Units Degrees Fahrenheit)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Maximum Temperature (Units Degrees Fahrenheit)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Maximum_Temperature_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Maximum_Temperature.csv"
Maximum_Temperature_df.to_csv(output_path, index=False)

Maximum_Temperature_df

,State,Year,January-December Maximum Temperature (Units Degrees Fahrenheit)
0,Alabama,1974,75.0
1,Alabama,1975,74.1
2,Alabama,1976,72.9
3,Alabama,1977,74.4
4,Alabama,1978,73.9
...,...,...,...
2445,Wyoming,2019,52.8
2446,Wyoming,2020,56.4
2447,Wyoming,2021,56.9
2448,Wyoming,2022,55.4
2449,Wyoming,2023,54.7

In [7]:
# Defining the correct folder path for Minimum Temperature
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Minimum Temperature"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 3 lines (header)
            df = pd.read_csv(file_path, skiprows=3)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Minimum Temperature')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Minimum Temperature (Units Degrees Fahrenheit)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Minimum Temperature (Units Degrees Fahrenheit)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Minimum_Temperature_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Minimum_Temperature.csv"
Minimum_Temperature_df.to_csv(output_path, index=False)

Minimum_Temperature_df

,State,Year,January-December Minimum Temperature (Units Degrees Fahrenheit)
0,Alabama,1974,51.2
1,Alabama,1975,51.6
2,Alabama,1976,48.4
3,Alabama,1977,50.6
4,Alabama,1978,49.8
...,...,...,...
2445,Wyoming,2019,27.8
2446,Wyoming,2020,29.1
2447,Wyoming,2021,30.4
2448,Wyoming,2022,28.5
2449,Wyoming,2023,29.4

In [8]:
# Defining the correct folder path for Palmer Drought Severity Index (PDSI)
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Palmer Drought Severity Index (PDSI)"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 2 lines (header)
            df = pd.read_csv(file_path, skiprows=2)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' August Palmer Drought Severity Index (PDSI)')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'August Palmer Drought Severity Index (PDSI)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'August Palmer Drought Severity Index (PDSI)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
PDSI_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/PDSI.csv"
PDSI_df.to_csv(output_path, index=False)

PDSI_df

        State  Year  August Palmer Drought Severity Index (PDSI)
0     Alabama  1974                                         1.99
1     Alabama  1975                                         4.54
2     Alabama  1976                                         2.65
3     Alabama  1977                                        -1.96
4     Alabama  1978                                        -0.37
...       ...   ...                                          ...
2395  Wyoming  2019                                         1.86
2396  Wyoming  2020                                        -2.44
2397  Wyoming  2021                                        -5.66
2398  Wyoming  2022                                        -4.33
2399  Wyoming  2023                                         3.24

[2400 rows x 3 columns]

In [9]:
# Defining the correct folder path for Palmer Hydrological Drought Index (PHDI)
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Palmer Hydrological Drought Index (PHDI)"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 2 lines (header)
            df = pd.read_csv(file_path, skiprows=2)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' August Palmer Hydrological Drought Index (PHDI)')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'August Palmer Hydrological Drought Index (PHDI)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'August Palmer Hydrological Drought Index (PHDI)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
PHDI_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/PHDI.csv"
PHDI_df.to_csv(output_path, index=False)

PHDI_df

        State  Year  August Palmer Hydrological Drought Index (PHDI)
0     Alabama  1974                                             1.99
1     Alabama  1975                                             4.54
2     Alabama  1976                                             2.65
3     Alabama  1977                                            -1.96
4     Alabama  1978                                             0.88
...       ...   ...                                              ...
2395  Wyoming  2019                                             1.86
2396  Wyoming  2020                                            -2.44
2397  Wyoming  2021                                            -5.66
2398  Wyoming  2022                                            -4.33
2399  Wyoming  2023                                             3.24

[2400 rows x 3 columns]

In [10]:
# Defining the correct folder path for Palmer Modified Drought Index (PMDI)
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Palmer Modified Drought Index (PMDI)"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 2 lines (header)
            df = pd.read_csv(file_path, skiprows=2)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' August Palmer Modified Drought Index (PMDI)')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'August Palmer Modified Drought Index (PMDI)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'August Palmer Modified Drought Index (PMDI)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
PMDI_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/PMDI.csv"
PMDI_df.to_csv(output_path, index=False)

PMDI_df

        State  Year  August Palmer Modified Drought Index (PMDI)
0     Alabama  1974                                         1.99
1     Alabama  1975                                         4.54
2     Alabama  1976                                         2.28
3     Alabama  1977                                        -1.96
4     Alabama  1978                                         0.12
...       ...   ...                                          ...
2395  Wyoming  2019                                         1.86
2396  Wyoming  2020                                        -2.44
2397  Wyoming  2021                                        -5.66
2398  Wyoming  2022                                        -4.33
2399  Wyoming  2023                                         3.24

[2400 rows x 3 columns]

In [11]:
# Defining the correct folder path for Palmer Z-Index
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Palmer Z-Index"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 2 lines (header)
            df = pd.read_csv(file_path, skiprows=2)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Palmer Z-Index')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Palmer Z-Index'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Palmer Z-Index']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Palmer_Z_Index_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Palmer_Z_Index.csv"
Palmer_Z_Index_df.to_csv(output_path, index=False)

Palmer_Z_Index_df

        State  Year  January-December Palmer Z-Index
0     Alabama  1974                             0.68
1     Alabama  1975                             1.86
2     Alabama  1976                             0.41
3     Alabama  1977                             0.01
4     Alabama  1978                            -0.42
...       ...   ...                              ...
2395  Wyoming  2019                             0.96
2396  Wyoming  2020                            -0.90
2397  Wyoming  2021                            -1.70
2398  Wyoming  2022                            -1.05
2399  Wyoming  2023                             1.05

[2400 rows x 3 columns]

In [12]:
# Defining the correct folder path for Precipitation
folder_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Precipitation"

# List to hold individual state dataframes
dfs = []

# Reading all csv files in the directory
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith(".csv"):
            file_path = os.path.join(root, filename)
            # print(f"Processing file: {file_path}")  # Add this line to track the file being processed

            # Reading the file while skipping the first 3 lines (header)
            df = pd.read_csv(file_path, skiprows=3)

            # Print columns to check structure
            # print("Columns in DataFrame:")
            # print(df.columns)

            # Extracting the state name from the first line
            with open(file_path, 'r') as f:
                state_info = f.readline().strip()
                state_name = state_info.split(' January-December Precipitation')[0]

            # Modifying the Date column to extract the Year
            if 'Date' in df.columns:
                df['Year'] = df['Date'].astype(str).str[:4].astype(int)

                # Dropping the 'Date' column
                df.drop(columns=['Date'], inplace=True)
            else:
                print("Warning: 'Date' column not found in DataFrame.")

            # Renaming the 'Value' column
            df.rename(columns={'Value': 'January-December Precipitation (Units Inches)'}, inplace=True)

            # Adding the State column
            df['State'] = state_name

            # Reordering the columns
            df = df[['State', 'Year', 'January-December Precipitation (Units Inches)']]

            # Appending the dataframe to the list
            dfs.append(df)

# Concatenating all dataframes into one
Precipitation_df = pd.concat(dfs, ignore_index=True)

# Saving the combined dataframe to a CSV file
output_path = "/content/drive/My Drive/GoodNotes/Climate_Data/Precipitation.csv"
Precipitation_df.to_csv(output_path, index=False)

Precipitation_df

        State  Year  January-December Precipitation (Units Inches)
0     Alabama  1974                                          60.40
1     Alabama  1975                                          74.76
2     Alabama  1976                                          55.98
3     Alabama  1977                                          57.87
4     Alabama  1978                                          49.50
...       ...   ...                                            ...
2445  Wyoming  2019                                          18.34
2446  Wyoming  2020                                          11.72
2447  Wyoming  2021                                          14.37
2448  Wyoming  2022                                          14.72
2449  Wyoming  2023                                          18.88

[2450 rows x 3 columns]

In [30]:
# Average_Temperature_df, Cooling_Degree_Days_df, Heating_Degree_Days_df, Maximum_Temperature_df,
# Minimum_Temperature_df, PDSI_df, PHDI_df, PMDI_df, Palmer_Z_Index_df, Precipitation_df

# Define a function to merge dataframes on 'State' and 'Year'
def merge_dfs(dfs):
    merged_df = pd.DataFrame({'State': [], 'Year': []})
    for df in dfs:
        merged_df = pd.merge(merged_df, df, on=['State', 'Year'], how='outer')
    return merged_df

# List of dataframes
dfs = [Average_Temperature_df, Cooling_Degree_Days_df, Heating_Degree_Days_df, Maximum_Temperature_df,
       Minimum_Temperature_df, PDSI_df, PHDI_df, PMDI_df, Palmer_Z_Index_df, Precipitation_df]

# Merge dataframes
initial_climate_variables_df = merge_dfs(dfs)
initial_climate_variables_df

,State,Year,January-December Average Temperature (Units Degrees Fahrenheit),January-December Cooling Degree Days (Units Fahrenheit Degree-Days),January-December Heating Degree Days (Units Fahrenheit Degree-Days),January-December Maximum Temperature (Units Degrees Fahrenheit),January-December Minimum Temperature (Units Degrees Fahrenheit),August Palmer Drought Severity Index (PDSI),August Palmer Hydrological Drought Index (PHDI),August Palmer Modified Drought Index (PMDI),January-December Palmer Z-Index,January-December Precipitation (Units Inches)
0,Alabama,1974,63.1,1594.0,2517.0,75.0,51.2,1.99,1.99,1.99,0.68,60.40
1,Alabama,1975,62.8,1659.0,2687.0,74.1,51.6,4.54,4.54,4.54,1.86,74.76
2,Alabama,1976,60.7,1424.0,3275.0,72.9,48.4,2.65,2.65,2.28,0.41,55.98
3,Alabama,1977,62.5,2020.0,3161.0,74.4,50.6,-1.96,-1.96,-1.96,0.01,57.87
4,Alabama,1978,61.9,1935.0,3317.0,73.9,49.8,-0.37,0.88,0.12,-0.42,49.50
...,...,...,...,...,...,...,...,...,...,...,...,...
2495,Wyoming,2019,40.3,246.0,8906.0,52.8,27.8,1.86,1.86,1.86,0.96,18.34
2496,Wyoming,2020,42.8,356.0,8069.0,56.4,29.1,-2.44,-2.44,-2.44,-0.90,11.72
2497,Wyoming,2021,43.6,413.0,7865.0,56.9,30.4,-5.66,-5.66,-5.66,-1.70,14.37
2498,Wyoming,2022,42.0,393.0,8441.0,55.4,28.5,-4.33,-4.33,-4.33,-1.05,14.72
2499,Wyoming,2023,42.0,254.0,8247.0,54.7,29.4,3.24,3.24,3.24,1.05,18.88

1) Palmer Drought Severity Index (PDSI):

The Palmer Drought Severity Index (PDSI) uses readily available temperature and precipitation data to estimate relative dryness. It is a standardized index that generally spans -10 (dry) to +10 (wet). The PDSI has been reasonably successful at quantifying long-term drought. As it uses temperature data and a physical water balance model, it can capture the basic effect of global warming on drought through changes in potential evapotranspiration. Monthly PDSI values do not capture droughts on time scales less than about 12 months.

2) Palmer Hydrological Drought Index (PHDI):

The PHDI is a component of the Palmer Drought Severity Index system that focuses specifically on hydrological aspects of drought.
It evaluates the impact of drought on groundwater and surface water resources by considering factors such as streamflow, groundwater recharge, and reservoir levels.
Like the PDSI, the PHDI provides a standardized measure of hydrological drought severity.

3) Palmer Modified Drought Index (PMDI):

The PMDI is a modified version of the original PDSI that incorporates additional factors to improve its accuracy, particularly in regions with nonstandard climates or in areas where the original PDSI may not perform well.
It may include adjustments to better represent the influence of factors such as snowmelt, irrigation, or other local conditions on drought severity.

4) Palmer Z-Index:

The Palmer Z-Index is a component of the Palmer Drought Severity Index system that focuses on short-term drought conditions.
It assesses drought severity over shorter timeframes, typically ranging from a few weeks to a few months.
The Z-Index evaluates deviations from normal precipitation and temperature conditions over these shorter periods to gauge the severity of short-term drought events.

5) Heating Degree Day (HDD): The number of heating degrees in a day is defined as the difference between 65Â°F and the mean temperature (average of the daily high and daily low).If the Average Daily Temperature is 30Â°F then the difference from 65Â°F is 35Â°F. Therefore, you have a 35 Heating Degree Day. In other words, you have had to heat the building by 35Â°F that day to reach 65Â°F.Mean daily temperature (MDT) = (Daily High Temp + Daily Low Temp)/2. HDD = 65Â°F â€“ MDT.

6) Cooling Degree Day (CDD): The number of cooling degrees in a day is defined as the difference between the mean temperature (average of the daily high and daily low) and 65Â°F. If the Average Daily Temperature is 80Â°F then the difference from 80Â°F to 65Â°F is 15Â°F. Therefore, you have a 15 Cooling Degree Day. In other words, you have had to cool the building by 15Â°F that day to reach 65Â°F. Mean daily temperature (MDT) = (Daily High Temp + Daily Low Temp)/2. CDD = MDT - 65Â°F

# 2. Merging initial climate variables with downloaded agricutural data.

In [31]:
file_path = "/content/drive/My Drive/GoodNotes/Agricultural Data/combined_agricultural_data.csv"
agri_df = pd.read_csv(file_path)
agri_df

,Year,State,Commodity,ACRES HARVESTED,"PRODUCTION, MEASURED IN $",YIELD
0,1974,ALABAMA,WHEAT,95000.0,2233000.0,23.5
1,1974,ARIZONA,WHEAT,200000.0,13000000.0,65.0
2,1974,ARKANSAS,WHEAT,330000.0,8745000.0,26.5
3,1974,CALIFORNIA,WHEAT,750000.0,37500000.0,50.0
4,1974,COLORADO,WHEAT,2900000.0,72625000.0,25.0
...,...,...,...,...,...,...
7592,2023,MINNESOTA,BEANS,207000.0,201200000.0,2430.0
7593,2023,NEBRASKA,BEANS,92000.0,82375000.0,2140.0
7594,2023,NORTH DAKOTA,BEANS,525000.0,340576000.0,1700.0
7595,2023,WASHINGTON,BEANS,31600.0,43912000.0,2760.0
7596,2023,WYOMING,BEANS,13300.0,14651000.0,2250.0

In [32]:
# Step 1: Normalize the "State" column in both dataframes to lowercase
agri_df['State_normalized'] = agri_df['State'].str.lower()  # Convert to lowercase for agri_df
initial_climate_variables_df['State_normalized'] = initial_climate_variables_df['State'].str.lower()  # Convert to lowercase for climate_df

# Step 2: Check for duplicates in climate_df based on "State_normalized" and "Year"
duplicate_rows = initial_climate_variables_df.duplicated(subset=['State_normalized', 'Year'], keep=False)
duplicate_entries = initial_climate_variables_df[duplicate_rows]

# Step 3: Investigate duplicate entries
if not duplicate_entries.empty:
    # Optionally, you can print or investigate duplicate entries
    print("Duplicate entries in climate_df:")
    print(duplicate_entries)

    # Depending on your data, decide how to handle duplicates
    # For example, you can aggregate data or drop duplicates
    # Here's an example of dropping duplicates based on "State_normalized" and "Year"
    initial_climate_variables_df.drop_duplicates(subset=['State_normalized', 'Year'], keep='first', inplace=True)

# Step 4: Merge the dataframes based on "State" and "Year" columns with a left join
initial_climate_agri_merg = pd.merge(agri_df, initial_climate_variables_df, on=['State_normalized', 'Year'], how='left')

# Step 5: Drop the additional columns added during merging if needed
initial_climate_agri_merg.drop(['State_y', 'State_normalized'], axis=1, inplace=True)

# Step 6: Rename the "State_x" column back to "State" and convert to lowercase
initial_climate_agri_merg.rename(columns={'State_x': 'State'}, inplace=True)
initial_climate_agri_merg['State'] = initial_climate_agri_merg['State'].str.lower()  # Convert "State" column to lowercase

initial_climate_agri_merg

Duplicate entries in climate_df:
        State  Year  \
2150  Vermont  1974
2151  Vermont  1974
2152  Vermont  1975
2153  Vermont  1975
2154  Vermont  1976
...       ...   ...
2245  Vermont  2021
2246  Vermont  2022
2247  Vermont  2022
2248  Vermont  2023
2249  Vermont  2023

      January-December Average Temperature (Units Degrees Fahrenheit)  \
2150                                               41.2
2151                                               41.2
2152                                               42.5
2153                                               42.5
2154                                               40.5
...                                                 ...
2245                                               45.0
2246                                               44.2
2247                                               44.2
2248                                               45.8
2249                                               45.8

      January-December Cooling Degree Days (Units Fahrenheit Degree-Days)  \
2150                                              156.0
2151                                              156.0
2152                                              250.0
2153                                              250.0
2154                                              148.0
...                                                 ...
2245                                              298.0
2246                                              294.0
2247                                              294.0
2248                                              265.0
2249                                              265.0

      January-December Heating Degree Days (Units Fahrenheit Degree-Days)  \
2150                                             8671.0
2151                                             8671.0
2152                                             8269.0
2153                                             8269.0
2154                                             8951.0
...                                                 ...
2245                                             7426.0
2246                                             7715.0
2247                                             7715.0
2248                                             7094.0
2249                                             7094.0

      January-December Maximum Temperature (Units Degrees Fahrenheit)  \
2150                                               51.8
2151                                               51.8
2152                                               53.1
2153                                               53.1
2154                                               51.4
...                                                 ...
2245                                               54.9
2246                                               55.4
2247                                               55.4
2248                                               55.5
2249                                               55.5

      January-December Minimum Temperature (Units Degrees Fahrenheit)  \
2150                                               30.6
2151                                               30.6
2152                                               31.8
2153                                               31.8
2154                                               29.5
...                                                 ...
2245                                               35.1
2246                                               33.1
2247                                               33.1
2248                                               36.1
2249                                               36.1

      August Palmer Drought Severity Index (PDSI)  \
2150                                         3.27
2151                                         3.27
2152                                         0.39
2153                                         0.39
2154                                         4.66
...                                           ...
2245                                         1.14
2246                                        -1.36
2247                                        -1.36
2248                                         4.06
2249                                         4.06

      August Palmer Hydrological Drought Index (PHDI)  \
2150                                             3.27
2151                                             3.27
2152                                            -0.66
2153                                            -0.66
2154                                             4.66
...                                               ...
2245                                            -1.29
2246                                            -1.36
2247                                            -1.36
2248                                             4.06
2249                                             4.06

      August Palmer Modified Drought Index (PMDI)  \
2150                                         3.27
2151                                         3.27
2152                                         0.19
2153                                         0.19
2154                                         4.66
...                                           ...
2245                                         0.29
2246                                        -1.36
2247                                        -1.36
2248                                         4.06
2249                                         4.06

      January-December Palmer Z-Index  \
2150                             0.72
2151                             0.72
2152                             0.48
2153                             0.48
2154                             1.45
...                               ...
2245                            -0.31
2246                            -0.04
2247                            -0.04
2248                             1.25
2249                             1.25

      January-December Precipitation (Units Inches) State_normalized
2150                                          46.26          vermont
2151                                          46.26          vermont
2152                                          47.67          vermont
2153                                          47.67          vermont
2154                                          53.00          vermont
...                                             ...              ...
2245                                          41.61          vermont
2246                                          43.92          vermont
2247                                          43.92          vermont
2248                                          53.50          vermont
2249                                          53.50          vermont

[100 rows x 13 columns]

,Year,State,Commodity,ACRES HARVESTED,"PRODUCTION, MEASURED IN $",YIELD,January-December Average Temperature (Units Degrees Fahrenheit),January-December Cooling Degree Days (Units Fahrenheit Degree-Days),January-December Heating Degree Days (Units Fahrenheit Degree-Days),January-December Maximum Temperature (Units Degrees Fahrenheit),January-December Minimum Temperature (Units Degrees Fahrenheit),August Palmer Drought Severity Index (PDSI),August Palmer Hydrological Drought Index (PHDI),August Palmer Modified Drought Index (PMDI),January-December Palmer Z-Index,January-December Precipitation (Units Inches)
0,1974,alabama,WHEAT,95000.0,2233000.0,23.5,63.1,1594.0,2517.0,75.0,51.2,1.99,1.99,1.99,0.68,60.40
1,1974,arizona,WHEAT,200000.0,13000000.0,65.0,59.5,2817.0,2282.0,73.9,45.1,-3.37,-3.37,-3.37,-0.67,10.99
2,1974,arkansas,WHEAT,330000.0,8745000.0,26.5,60.3,1437.0,3317.0,71.0,49.5,3.80,3.80,3.80,1.01,58.81
3,1974,california,WHEAT,750000.0,37500000.0,50.0,57.6,751.0,3300.0,70.2,45.1,-0.48,1.17,0.24,-0.12,21.35
4,1974,colorado,WHEAT,2900000.0,72625000.0,25.0,44.4,224.0,7459.0,58.6,30.2,-2.29,-2.29,-2.29,-0.67,14.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,2023,minnesota,BEANS,207000.0,201200000.0,2430.0,43.8,578.0,7820.0,54.1,33.6,-3.76,-3.76,-3.76,-0.88,24.04
7593,2023,nebraska,BEANS,92000.0,82375000.0,2140.0,50.4,1115.0,5845.0,62.9,37.8,-2.95,-2.95,-2.58,-0.16,24.78
7594,2023,north dakota,BEANS,525000.0,340576000.0,1700.0,42.1,576.0,8915.0,53.1,31.0,0.65,0.65,-0.49,0.01,17.45
7595,2023,washington,BEANS,31600.0,43912000.0,2760.0,48.4,269.0,5347.0,58.0,38.8,-3.47,-3.47,-3.47,-1.15,35.84
7596,2023,wyoming,BEANS,13300.0,14651000.0,2250.0,42.0,254.0,8247.0,54.7,29.4,3.24,3.24,3.24,1.05,18.88

In [33]:
# Define the file path to save the CSV
file_path = '/content/drive/My Drive/GoodNotes/Agricultural Data/Merged_Agri_Initial_Climate_Data.csv'

# Save merged_df as a CSV file
initial_climate_agri_merg.to_csv(file_path, index=False)

print(f"Data has been successfully saved to: {file_path}")

Data has been successfully saved to: /content/drive/My Drive/GoodNotes/Agricultural Data/Merged_Agri__Initial_Climate_Data.csv

# 3. Additional Climate Variables.

In [21]:
# Path to the folder containing the CSV files
folder_path = "/content/drive/My Drive/GoodNotes/Additional Climate Data"

# List all files in the directory
file_names = os.listdir(folder_path)
csv_files = [f for f in file_names if f.endswith('.csv')]

print(csv_files)

['Washington.csv', 'Oregon.csv', 'California.csv', 'Nevada.csv', 'Arizona.csv', 'Utah.csv', 'Idaho.csv', 'Montana.csv', 'Wyoming.csv', 'Colorado.csv', 'New Mexico.csv', 'Texas.csv', 'Oklahoma.csv', 'Kansas.csv', 'Nebraska.csv', 'South Dakota.csv', 'North Dakota.csv', 'Minnesota.csv', 'Iowa.csv', 'Missouri.csv', 'Arkansas.csv', 'Louisiana.csv', 'Mississippi.csv', 'Alabama.csv', 'Georgia.csv', 'Florida.csv', 'South Carolina.csv', 'North Carolina.csv', 'Tennessee.csv', 'Kentucky.csv', 'Illinois.csv', 'Wisconsin.csv', 'Michigan.csv', 'Indiana.csv', 'Ohio.csv', 'West Virginia.csv', 'Virginia.csv', 'Maryland.csv', 'Delaware.csv', 'Pennsylvania.csv', 'New Jersey.csv', 'New York.csv', 'Connecticut.csv', 'Rhode Island.csv', 'Massachusetts.csv', 'Vermont.csv', 'New Hampshire.csv', 'Maine.csv', 'Hawaii.csv', 'Alaska.csv', 'combined_data.csv']

In [22]:
# Column names to be set for each DataFrame
new_column_names = ["PARAMETER", "YEAR", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC", "ANN"]

# Dictionary to store DataFrames
dataframes = {}

for file in csv_files:
    file_path = os.path.join(folder_path, file)
    try:
        with open(file_path, 'r') as f:
            lines = f.readlines()
            # Find the line number where '-END HEADER-' is located
            start_line = 0
            for i, line in enumerate(lines):
                if '-END HEADER-' in line:
                    start_line = i + 1
                    break
            # Create a DataFrame from the data starting after the header
            data = ''.join(lines[start_line:])
            df = pd.read_csv(io.StringIO(data))
            # Check if the DataFrame has the correct number of columns
            if df.shape[1] == len(new_column_names):
                # Set the new column names
                df.columns = new_column_names
                # Drop all columns except 'PARAMETER', 'YEAR', and 'ANN'
                df = df[['PARAMETER', 'YEAR', 'ANN']]
                # Store the DataFrame in the dictionary
                dataframes[file] = df
            else:
                print(f"File {file} does not have the expected number of columns after processing.")
    except Exception as e:
        print(f"Error processing {file}: {e}")

# Example: Accessing the DataFrame for the first CSV file after processing
if csv_files:
    first_file = csv_files[0]
    if first_file in dataframes:
        print(dataframes[first_file].head())
else:
    print("No CSV files found in the directory.")

File combined_data.csv does not have the expected number of columns after processing.
  PARAMETER  YEAR    ANN
0        PS  1981  90.11
1        PS  1982  90.03
2        PS  1983  89.94
3        PS  1984  90.11
4        PS  1985  90.26

In [24]:
# Add 'state' column to each DataFrame
for file in dataframes:
    state_name = os.path.splitext(file)[0]  # Get the state name by removing the .csv extension
    dataframes[file]['state'] = state_name

# Example: Accessing the DataFrame for the first CSV file after adding the 'state' column
first_file = list(dataframes.keys())[0]
print(dataframes[first_file].head())

  PARAMETER  YEAR    ANN       state
0        PS  1981  90.11  Washington
1        PS  1982  90.03  Washington
2        PS  1983  89.94  Washington
3        PS  1984  90.11  Washington
4        PS  1985  90.26  Washington

In [25]:
# Transform each DataFrame in the dictionary
for file, df in dataframes.items():
    # Pivot the DataFrame
    pivot_df = df.pivot(index=['YEAR', 'state'], columns='PARAMETER', values='ANN').reset_index()

    # Update the DataFrame in the dictionary
    dataframes[file] = pivot_df

# Example: Accessing the transformed DataFrame for the first CSV file
first_file = list(dataframes.keys())[0]
print(dataframes[first_file].head())

PARAMETER  YEAR       state  ALLSKY_SFC_PAR_TOT  ALLSKY_SFC_SW_DIFF  \
0          1981  Washington                 NaN                 NaN
1          1982  Washington                 NaN                 NaN
2          1983  Washington                 NaN                 NaN
3          1984  Washington                 NaN                 NaN
4          1985  Washington                 NaN                 NaN

PARAMETER  ALLSKY_SFC_SW_DNI  ALLSKY_SFC_SW_DWN  ALLSKY_SFC_UVA  \
0                        NaN                NaN             NaN
1                        NaN                NaN             NaN
2                        NaN                NaN             NaN
3                        NaN              13.22             NaN
4                        NaN              14.06             NaN

PARAMETER  ALLSKY_SFC_UVB  ALLSKY_SFC_UV_INDEX  ALLSKY_SRF_ALB  ...  QV2M  \
0                     NaN                  NaN             NaN  ...  4.88
1                     NaN                  NaN             NaN  ...  4.76
2                     NaN                  NaN             NaN  ...  4.94
3                     NaN                  NaN            0.22  ...  4.70
4                     NaN                  NaN            0.18  ...  4.39

PARAMETER   RH2M  T2MDEW  T2MWET  TOA_SW_DWN    TS   WD10M    WD2M  WS10M  \
0          76.62    0.96    3.34         NaN  5.15  288.31  295.44   2.18
1          78.81    0.15    2.26         NaN  3.58  287.75  294.62   2.10
2          80.56    0.87    2.79         NaN  4.01  295.56  304.56   2.14
3          80.00    0.26    2.21       25.51  3.54  282.56  286.75   2.20
4          77.62   -1.04    1.30       25.55  2.72  293.88  300.44   2.18

PARAMETER  WS2M
0          0.63
1          0.62
2          0.62
3          0.62
4          0.64

[5 rows x 27 columns]

In [34]:
# List to hold all DataFrames for concatenation
df_list = []

# Iterate through the DataFrames in the dictionary and add them to the list
for df in dataframes.values():
    df_list.append(df)

# Concatenate all DataFrames in the list into a single DataFrame
additional_climate_df = pd.concat(df_list, ignore_index=True)

additional_climate_df

PARAMETER,YEAR,state,ALLSKY_SFC_PAR_TOT,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_UVA,ALLSKY_SFC_UVB,ALLSKY_SFC_UV_INDEX,ALLSKY_SRF_ALB,...,QV2M,RH2M,T2MDEW,T2MWET,TOA_SW_DWN,TS,WD10M,WD2M,WS10M,WS2M
0,1981,Washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.88,76.62,0.96,3.34,NaN,5.15,288.31,295.44,2.18,0.63
1,1982,Washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.76,78.81,0.15,2.26,NaN,3.58,287.75,294.62,2.10,0.62
2,1983,Washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.94,80.56,0.87,2.79,NaN,4.01,295.56,304.56,2.14,0.62
3,1984,Washington,NaN,NaN,NaN,13.22,NaN,NaN,NaN,0.22,...,4.70,80.00,0.26,2.21,25.51,3.54,282.56,286.75,2.20,0.62
4,1985,Washington,NaN,NaN,NaN,14.06,NaN,NaN,NaN,0.18,...,4.39,77.62,-1.04,1.30,25.55,2.72,293.88,300.44,2.18,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2095,2018,Alaska,46.16,4.67,12.04,9.24,6.01,0.08,NaN,0.21,...,3.72,90.50,-4.91,-4.02,18.65,-3.60,55.81,58.06,2.30,0.70
2096,2019,Alaska,45.16,4.70,11.00,9.06,5.77,0.08,NaN,0.20,...,4.03,90.19,-4.16,-3.22,18.65,-2.70,50.75,57.88,2.38,0.73
2097,2020,Alaska,46.06,4.64,11.95,9.24,5.96,0.08,NaN,0.23,...,3.72,91.31,-6.33,-5.54,18.61,-5.22,51.62,55.06,2.31,0.72
2098,2021,Alaska,45.95,4.68,11.80,9.25,5.95,0.08,NaN,0.23,...,3.54,90.75,-7.05,-6.20,18.66,-5.83,47.19,50.69,2.27,0.70
2099,2022,Alaska,47.40,4.50,12.71,9.54,6.10,0.08,NaN,0.21,...,3.66,90.31,-6.12,-5.22,18.67,-4.73,51.38,51.50,2.44,0.78

In [36]:
# Define the file path in Google Drive
output_file_path = '/content/drive/My Drive/GoodNotes/Additional Climate Data/combined_data.csv'

# Save the combined DataFrame to a CSV file
additional_climate_df.to_csv(output_file_path, index=False)

print(f"Combined DataFrame saved to {output_file_path}")

Combined DataFrame saved to /content/drive/My Drive/GoodNotes/Additional Climate Data/combined_data.csv

# 4. Merging "Merged_Agri__Initial_Climate_Data.csv" with additional climate variables.

In [40]:
# Specify the file path
file_path = '/content/drive/My Drive/GoodNotes/Agricultural Data/Merged_Agri__Initial_Climate_Data.csv'

# Read the CSV file into a DataFrame
merged_df = pd.read_csv(file_path)

merged_df

,Year,State,Commodity,ACRES HARVESTED,"PRODUCTION, MEASURED IN $",YIELD,January-December Average Temperature (Units Degrees Fahrenheit),January-December Cooling Degree Days (Units Fahrenheit Degree-Days),January-December Heating Degree Days (Units Fahrenheit Degree-Days),January-December Maximum Temperature (Units Degrees Fahrenheit),January-December Minimum Temperature (Units Degrees Fahrenheit),August Palmer Drought Severity Index (PDSI),August Palmer Hydrological Drought Index (PHDI),August Palmer Modified Drought Index (PMDI),January-December Palmer Z-Index,January-December Precipitation (Units Inches)
0,1974,alabama,WHEAT,95000.0,2233000.0,23.5,63.1,1594.0,2517.0,75.0,51.2,1.99,1.99,1.99,0.68,60.40
1,1974,arizona,WHEAT,200000.0,13000000.0,65.0,59.5,2817.0,2282.0,73.9,45.1,-3.37,-3.37,-3.37,-0.67,10.99
2,1974,arkansas,WHEAT,330000.0,8745000.0,26.5,60.3,1437.0,3317.0,71.0,49.5,3.80,3.80,3.80,1.01,58.81
3,1974,california,WHEAT,750000.0,37500000.0,50.0,57.6,751.0,3300.0,70.2,45.1,-0.48,1.17,0.24,-0.12,21.35
4,1974,colorado,WHEAT,2900000.0,72625000.0,25.0,44.4,224.0,7459.0,58.6,30.2,-2.29,-2.29,-2.29,-0.67,14.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,2023,minnesota,BEANS,207000.0,201200000.0,2430.0,43.8,578.0,7820.0,54.1,33.6,-3.76,-3.76,-3.76,-0.88,24.04
7593,2023,nebraska,BEANS,92000.0,82375000.0,2140.0,50.4,1115.0,5845.0,62.9,37.8,-2.95,-2.95,-2.58,-0.16,24.78
7594,2023,north dakota,BEANS,525000.0,340576000.0,1700.0,42.1,576.0,8915.0,53.1,31.0,0.65,0.65,-0.49,0.01,17.45
7595,2023,washington,BEANS,31600.0,43912000.0,2760.0,48.4,269.0,5347.0,58.0,38.8,-3.47,-3.47,-3.47,-1.15,35.84
7596,2023,wyoming,BEANS,13300.0,14651000.0,2250.0,42.0,254.0,8247.0,54.7,29.4,3.24,3.24,3.24,1.05,18.88

In [42]:
# Specify the file path
file_path = '/content/drive/My Drive/GoodNotes/Additional Climate Data/combined_data.csv'

# Read the CSV file into a DataFrame
add_climate_df = pd.read_csv(file_path)

# Capitalize all column names
add_climate_df.columns = [col.title() for col in add_climate_df.columns]

# Convert the contents of the 'State' column to lowercase
add_climate_df['State'] = add_climate_df['State'].str.lower()

add_climate_df

,Year,State,Allsky_Sfc_Par_Tot,Allsky_Sfc_Sw_Diff,Allsky_Sfc_Sw_Dni,Allsky_Sfc_Sw_Dwn,Allsky_Sfc_Uva,Allsky_Sfc_Uvb,Allsky_Sfc_Uv_Index,Allsky_Srf_Alb,...,Qv2M,Rh2M,T2Mdew,T2Mwet,Toa_Sw_Dwn,Ts,Wd10M,Wd2M,Ws10M,Ws2M
0,1981,washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.88,76.62,0.96,3.34,NaN,5.15,288.31,295.44,2.18,0.63
1,1982,washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.76,78.81,0.15,2.26,NaN,3.58,287.75,294.62,2.10,0.62
2,1983,washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.94,80.56,0.87,2.79,NaN,4.01,295.56,304.56,2.14,0.62
3,1984,washington,NaN,NaN,NaN,13.22,NaN,NaN,NaN,0.22,...,4.70,80.00,0.26,2.21,25.51,3.54,282.56,286.75,2.20,0.62
4,1985,washington,NaN,NaN,NaN,14.06,NaN,NaN,NaN,0.18,...,4.39,77.62,-1.04,1.30,25.55,2.72,293.88,300.44,2.18,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2095,2018,alaska,46.16,4.67,12.04,9.24,6.01,0.08,NaN,0.21,...,3.72,90.50,-4.91,-4.02,18.65,-3.60,55.81,58.06,2.30,0.70
2096,2019,alaska,45.16,4.70,11.00,9.06,5.77,0.08,NaN,0.20,...,4.03,90.19,-4.16,-3.22,18.65,-2.70,50.75,57.88,2.38,0.73
2097,2020,alaska,46.06,4.64,11.95,9.24,5.96,0.08,NaN,0.23,...,3.72,91.31,-6.33,-5.54,18.61,-5.22,51.62,55.06,2.31,0.72
2098,2021,alaska,45.95,4.68,11.80,9.25,5.95,0.08,NaN,0.23,...,3.54,90.75,-7.05,-6.20,18.66,-5.83,47.19,50.69,2.27,0.70
2099,2022,alaska,47.40,4.50,12.71,9.54,6.10,0.08,NaN,0.21,...,3.66,90.31,-6.12,-5.22,18.67,-4.73,51.38,51.50,2.44,0.78

In [43]:
agri_climate_df = pd.merge(merged_df, add_climate_df, on=['State', 'Year'])
agri_climate_df

,Year,State,Commodity,ACRES HARVESTED,"PRODUCTION, MEASURED IN $",YIELD,January-December Average Temperature (Units Degrees Fahrenheit),January-December Cooling Degree Days (Units Fahrenheit Degree-Days),January-December Heating Degree Days (Units Fahrenheit Degree-Days),January-December Maximum Temperature (Units Degrees Fahrenheit),...,Qv2M,Rh2M,T2Mdew,T2Mwet,Toa_Sw_Dwn,Ts,Wd10M,Wd2M,Ws10M,Ws2M
0,1981,alabama,WHEAT,565000.0,2.486000e+07,44.0,62.0,1793.0,3126.0,74.3,...,8.91,70.69,10.05,13.23,NaN,16.26,271.69,248.38,1.94,0.26
1,1981,alabama,POTATOES,13100.0,2.285900e+07,159.0,62.0,1793.0,3126.0,74.3,...,8.91,70.69,10.05,13.23,NaN,16.26,271.69,248.38,1.94,0.26
2,1981,alabama,CORN,530000.0,7.870500e+07,55.0,62.0,1793.0,3126.0,74.3,...,8.91,70.69,10.05,13.23,NaN,16.26,271.69,248.38,1.94,0.26
3,1981,alabama,COTTON,372000.0,1.132310e+08,545.0,62.0,1793.0,3126.0,74.3,...,8.91,70.69,10.05,13.23,NaN,16.26,271.69,248.38,1.94,0.26
4,1981,arizona,WHEAT,258000.0,2.184400e+07,84.7,61.3,2987.0,1782.0,75.4,...,5.19,50.62,-0.46,5.48,NaN,10.68,215.31,225.62,2.45,0.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6434,2022,iowa,CORN,12350000.0,1.635140e+10,200.0,47.5,902.0,7209.0,58.7,...,6.53,70.56,3.44,6.33,27.48,9.40,264.25,268.50,5.18,3.58
6435,2022,louisiana,CORN,435000.0,4.925070e+08,170.0,67.3,2790.0,1686.0,78.2,...,11.29,76.00,14.02,16.56,31.14,19.01,161.94,158.88,2.09,0.38
6436,2022,louisiana,RICE,412000.0,4.667010e+08,6660.0,67.3,2790.0,1686.0,78.2,...,11.29,76.00,14.02,16.56,31.14,19.01,161.94,158.88,2.09,0.38
6437,2022,louisiana,COTTON,190000.0,1.589520e+08,904.0,67.3,2790.0,1686.0,78.2,...,11.29,76.00,14.02,16.56,31.14,19.01,161.94,158.88,2.09,0.38
6438,2022,west virginia,CORN,30000.0,3.477600e+07,168.0,52.4,815.0,5190.0,63.7,...,7.69,76.88,6.55,8.78,28.91,10.74,223.69,227.75,2.24,0.21

In [45]:
# Specify the file path where you want to save the DataFrame
save_path = '/content/drive/My Drive/GoodNotes/Merged File for Analysis/Complete_Agri_Climate.csv'

# Save the DataFrame to the specified file path
agri_climate_df.to_csv(save_path, index=False)

# 5. Retriving Socioeconomic Data

## 5.1 Using API to retrieve DGP, Population, Personal Income Variables by each State.

In [48]:
# Replace 'YOUR_BEA_API_KEY' with your actual BEA API key
bea_api_key = '5DFE2696-DC1C-4E7D-B1A2-35756560727C'

# Function to fetch data from BEA API
def fetch_bea_data(table_name, line_code, description):
    url = 'https://apps.bea.gov/api/data/'
    params = {
        'UserID': bea_api_key,
        'method': 'GetData',
        'datasetname': 'Regional',
        'TableName': table_name,
        'LineCode': line_code,
        'Year': 'ALL',    # Fetch all available years
        'GeoFIPS': 'STATE',  # Fetch data for all states
        'ResultFormat': 'JSON'
    }

    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        # Extract data and create DataFrame
        data_records = data['BEAAPI']['Results']['Data']
        df = pd.DataFrame(data_records)

        # Print DataFrame columns and first few rows for inspection
        print(f"Data for {description} columns: {df.columns.tolist()}")
        print(df.head())

        return df
    else:
        print(f"Error: Unable to fetch {description} data (Status code: {response.status_code})")
        return pd.DataFrame()

# Fetch data
gdp_data = fetch_bea_data('SAINC1', '1', 'GDP')
population_data = fetch_bea_data('SAINC1', '2', 'Population')
personal_income_data = fetch_bea_data('SAINC1', '3', 'Personal Income')

# Print columns for each DataFrame to verify names
print("GDP Data Columns:", gdp_data.columns.tolist())
print("Population Data Columns:", population_data.columns.tolist())
print("Personal Income Data Columns:", personal_income_data.columns.tolist())

# Rename columns to standardize them for merging
gdp_data.rename(columns={'GeoFips': 'GeoFIPS', 'DataValue': 'GDP'}, inplace=True)
population_data.rename(columns={'GeoFips': 'GeoFIPS', 'DataValue': 'Population'}, inplace=True)
personal_income_data.rename(columns={'GeoFips': 'GeoFIPS', 'DataValue': 'Personal Income'}, inplace=True)

# Use 'GeoName' as 'State' directly
gdp_data['State'] = gdp_data['GeoName']
population_data['State'] = population_data['GeoName']
personal_income_data['State'] = personal_income_data['GeoName']

# Drop the 'GeoName' column if no longer needed
gdp_data.drop(columns=['GeoName'], inplace=True)
population_data.drop(columns=['GeoName'], inplace=True)
personal_income_data.drop(columns=['GeoName'], inplace=True)

# Clean the 'State' column by removing any trailing characters like '*'
for df in [gdp_data, population_data, personal_income_data]:
    df['State'] = df['State'].str.replace(r'\*$', '', regex=True).str.strip()

# Define common columns
common_columns = ['State', 'TimePeriod']

# Merge the DataFrames
merged_df = gdp_data.merge(population_data, on=common_columns, suffixes=('_GDP', '_Population'))
merged_df = merged_df.merge(personal_income_data, on=common_columns)

# Rename columns for clarity and append units
GDP_Pop_Inco = merged_df.rename(columns={
    'TimePeriod': 'Year',
    'GDP': 'GDP (Millions of dollars)',
    'Population': 'Population (Number of persons)',
    'Personal Income': 'Personal Income (Dollars)'
})[['State', 'Year', 'GDP (Millions of dollars)', 'Population (Number of persons)', 'Personal Income (Dollars)']]

# Convert 'Year' to integer
GDP_Pop_Inco['Year'] = GDP_Pop_Inco['Year'].astype(int)

# Filter the data for the years 1974 to 2023
GDP_Pop_Inco_df = GDP_Pop_Inco[(GDP_Pop_Inco['Year'] >= 1974) & (GDP_Pop_Inco['Year'] <= 2023)]

# Define the file path
file_path = '/content/drive/My Drive/GoodNotes/Economic Data/GDP_Population_Income_1974_2023.csv'

# Save the DataFrame to CSV
GDP_Pop_Inco_df.to_csv(file_path, index=False)

print(f"Data saved to {file_path}")

Data for GDP columns: ['Code', 'GeoFips', 'GeoName', 'TimePeriod', 'CL_UNIT', 'UNIT_MULT', 'DataValue', 'NoteRef']
       Code GeoFips        GeoName TimePeriod              CL_UNIT UNIT_MULT  \
0  SAINC1-1   00000  United States       2023  Millions of dollars         6
1  SAINC1-1   00000  United States       1947  Millions of dollars         6
2  SAINC1-1   00000  United States       1980  Millions of dollars         6
3  SAINC1-1   00000  United States       2006  Millions of dollars         6
4  SAINC1-1   00000  United States       1984  Millions of dollars         6

    DataValue NoteRef
0  22952028.3     NaN
1    192525.0     NaN
2   2313972.0     NaN
3  11291446.0     NaN
4   3275415.0     NaN
Data for Population columns: ['Code', 'GeoFips', 'GeoName', 'TimePeriod', 'CL_UNIT', 'UNIT_MULT', 'DataValue', 'NoteRef']
       Code GeoFips        GeoName TimePeriod            CL_UNIT UNIT_MULT  \
0  SAINC1-2   00000  United States       1930  Number of persons         0
1  SAINC1-2   00000  United States       1931  Number of persons         0
2  SAINC1-2   00000  United States       1933  Number of persons         0
3  SAINC1-2   00000  United States       1934  Number of persons         0
4  SAINC1-2   00000  United States       1935  Number of persons         0

   DataValue NoteRef
0  123075000       1
1  124038000       1
2  125580000       1
3  126372000       1
4  127251000       1
Data for Personal Income columns: ['Code', 'GeoFips', 'GeoName', 'TimePeriod', 'CL_UNIT', 'UNIT_MULT', 'DataValue', 'NoteRef']
       Code GeoFips        GeoName TimePeriod  CL_UNIT UNIT_MULT DataValue  \
0  SAINC1-3   00000  United States       1930  Dollars         0       621
1  SAINC1-3   00000  United States       1931  Dollars         0       528
2  SAINC1-3   00000  United States       1933  Dollars         0       375
3  SAINC1-3   00000  United States       1934  Dollars         0       427
4  SAINC1-3   00000  United States       1935  Dollars         0       477

  NoteRef
0       2
1       2
2       2
3       2
4       2
GDP Data Columns: ['Code', 'GeoFips', 'GeoName', 'TimePeriod', 'CL_UNIT', 'UNIT_MULT', 'DataValue', 'NoteRef']
Population Data Columns: ['Code', 'GeoFips', 'GeoName', 'TimePeriod', 'CL_UNIT', 'UNIT_MULT', 'DataValue', 'NoteRef']
Personal Income Data Columns: ['Code', 'GeoFips', 'GeoName', 'TimePeriod', 'CL_UNIT', 'UNIT_MULT', 'DataValue', 'NoteRef']
Data saved to /content/drive/My Drive/GoodNotes/Economic Data/GDP_Population_Income_1974_2023.csv

In [49]:
file_path = '/content/drive/My Drive/GoodNotes/Economic Data/GDP_Population_Income_1974_2023.csv'

# Load the DataFrame from the CSV file
GDP_Pop_Inco_df = pd.read_csv(file_path)

GDP_Pop_Inco_df

,State,Year,GDP (Millions of dollars),Population (Number of persons),Personal Income (Dollars)
0,United States,2023,22952028.3,334914895,68531
1,United States,1980,2313972.0,227224719,10184
2,United States,2006,11291446.0,298379912,37843
3,United States,1984,3275415.0,235824907,13889
4,United States,2017,16658962.0,326623063,51004
...,...,...,...,...,...
2995,Far West,2020,3828494.5,56772795,67435
2996,Far West,2022,4193955.2,56414568,74342
2997,Far West,2015,2886096.5,55207598,52277
2998,Far West,2016,3016423.1,55738346,54118
2999,Far West,2014,2697504.9,54651324,49358

In [50]:
# Define the file path
file_path = '/content/drive/My Drive/GoodNotes/Economic Data/GDP_Population_Income_1974_2023.csv'

GDP_Pop_Inco_df = pd.read_csv(file_path)

GDP_Pop_Inco_df

,State,Year,GDP (Millions of dollars),Population (Number of persons),Personal Income (Dollars)
0,United States,2023,22952028.3,334914895,68531
1,United States,1980,2313972.0,227224719,10184
2,United States,2006,11291446.0,298379912,37843
3,United States,1984,3275415.0,235824907,13889
4,United States,2017,16658962.0,326623063,51004
...,...,...,...,...,...
2995,Far West,2020,3828494.5,56772795,67435
2996,Far West,2022,4193955.2,56414568,74342
2997,Far West,2015,2886096.5,55207598,52277
2998,Far West,2016,3016423.1,55738346,54118
2999,Far West,2014,2697504.9,54651324,49358

## 5.2 Downloaded Kaggle Dataset: Employment and Unemployment Data 1976-2022

In [51]:
file_path = '/content/drive/My Drive/GoodNotes/Economic Data/Unemployment_1976_2022.csv'
unemployment_df = pd.read_csv(file_path)
unemployment_df

,FIPS Code,State/Area,Year,Month,Total Civilian Non-Institutional Population in State/Area,Total Civilian Labor Force in State/Area,Percent (%) of State/Area's Population,Total Employment in State/Area,Percent (%) of Labor Force Employed in State/Area,Total Unemployment in State/Area,Percent (%) of Labor Force Unemployed in State/Area
0,1,Alabama,1976,1,"2,605,000","1,484,555",57.0,"1,386,023",53.2,"98,532",6.6
1,2,Alaska,1976,1,"232,000","160,183",69.0,"148,820",64.1,"11,363",7.1
2,4,Arizona,1976,1,"1,621,000","964,120",59.5,"865,871",53.4,"98,249",10.2
3,5,Arkansas,1976,1,"1,536,000","889,044",57.9,"824,395",53.7,"64,649",7.3
4,6,California,1976,1,"15,621,000","9,774,280",62.6,"8,875,685",56.8,"898,595",9.2
...,...,...,...,...,...,...,...,...,...,...,...
29887,51,Virginia,2022,12,"6,862,585","4,470,272",65.1,"4,330,531",63.1,"139,741",3.1
29888,53,Washington,2022,12,"6,254,253","4,015,286",64.2,"3,832,769",61.3,"182,517",4.5
29889,54,West Virginia,2022,12,"1,434,789","784,323",54.7,"752,464",52.4,"31,859",4.1
29890,55,Wisconsin,2022,12,"4,753,700","3,068,610",64.6,"2,976,670",62.6,"91,940",3.0
29891,56,Wyoming,2022,12,"460,134","293,595",63.8,"282,247",61.3,"11,348",3.9

In [52]:
# Taking Annaul Average for the employment and unemployment dataset
# Remove commas and convert columns to numeric
cols_to_convert = [
    'Total Civilian Non-Institutional Population in State/Area',
    'Total Civilian Labor Force in State/Area',
    'Total Employment in State/Area',
    'Total Unemployment in State/Area'
]

for col in cols_to_convert:
    unemployment_df[col] = unemployment_df[col].str.replace(',', '').astype(float)

# Group by 'State/Area' and 'Year', calculate the mean, and reset index
annual_avg_unemply_df = unemployment_df.groupby(['State/Area', 'Year']).mean().reset_index()

# Drop the 'Month' column as it is no longer needed
annual_avg_unemply_df = annual_avg_unemply_df.drop(columns=['Month'])


# Set display options to avoid scientific notation
pd.set_option('display.float_format', '{:.0f}'.format)


annual_avg_unemply_df

,State/Area,Year,FIPS Code,Total Civilian Non-Institutional Population in State/Area,Total Civilian Labor Force in State/Area,Percent (%) of State/Area's Population,Total Employment in State/Area,Percent (%) of Labor Force Employed in State/Area,Total Unemployment in State/Area,Percent (%) of Labor Force Unemployed in State/Area
0,Alabama,1976,1,2632667,1500260,57,1399782,53,100478,7
1,Alabama,1977,1,2688917,1564380,58,1452654,54,111726,7
2,Alabama,1978,1,2745083,1621167,59,1517318,55,103849,6
3,Alabama,1979,1,2790583,1661266,60,1541184,55,120082,7
4,Alabama,1980,1,2829250,1679660,59,1531546,54,148114,9
...,...,...,...,...,...,...,...,...,...,...
2486,Wyoming,2018,56,445661,292595,66,280732,63,11862,4
2487,Wyoming,2019,56,447440,293375,66,282455,63,10920,4
2488,Wyoming,2020,56,450627,293736,65,276388,61,17347,6
2489,Wyoming,2021,56,454147,289154,64,275786,61,13368,5
2490,Wyoming,2022,56,457895,291721,64,281332,61,10389,4

## 5.3 Combining GDP Population Personal Income dataframe and annual averaged Emploement and Unemployment Dataset.

In [53]:
# Rename the 'State/Area' column in annual_avg_unemply_df to 'State' to match GDP_Pop_Inco_df
annual_avg_unemply_df.rename(columns={'State/Area': 'State'}, inplace=True)

# Merge the two dataframes on 'State' and 'Year' columns
eco_socie_df = pd.merge(GDP_Pop_Inco_df, annual_avg_unemply_df, on=['State', 'Year'])

# Filter the dataframe to include only the years from 1976 to 2022
eco_socie_df = eco_socie_df[(eco_socie_df['Year'] >= 1976) & (eco_socie_df['Year'] <= 2022)]

# Display the resulting dataframe
eco_socie_df

,State,Year,GDP (Millions of dollars),Population (Number of persons),Personal Income (Dollars),FIPS Code,Total Civilian Non-Institutional Population in State/Area,Total Civilian Labor Force in State/Area,Percent (%) of State/Area's Population,Total Employment in State/Area,Percent (%) of Labor Force Employed in State/Area,Total Unemployment in State/Area,Percent (%) of Labor Force Unemployed in State/Area
0,Alabama,1988,55527,4023842,13800,1,3057500,1874603,61,1738008,57,136594,7
1,Alabama,2010,162069,4787998,33849,1,3690247,2196694,60,1968757,53,227938,10
2,Alabama,1999,103204,4430141,23296,1,3361672,2150126,64,2048692,61,101435,5
3,Alabama,2021,252792,5050380,50054,1,3989929,2259433,57,2183167,55,76267,3
4,Alabama,1995,85394,4296800,19874,1,3253839,2065910,63,1945244,60,120666,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,Wyoming,2020,37866,577664,65551,56,450627,293736,65,276388,61,17347,6
2393,Wyoming,2022,42585,581629,73216,56,457895,291721,64,281332,61,10389,4
2394,Wyoming,2015,32756,583645,56122,56,451235,301677,67,288927,64,12750,4
2395,Wyoming,2016,31090,581983,53421,56,450992,300464,67,284450,63,16015,5
2396,Wyoming,2014,32680,580949,56252,56,449700,302865,67,289699,64,13166,4

In [54]:
file_path = '/content/drive/My Drive/GoodNotes/Economic Data/Economy_Society.csv'
eco_socie_df.to_csv(file_path, index=False)

# 6. Merging Socioeconomic Dataset with Complete Agricutual and Climate Data.

In [55]:
file_path = '/content/drive/My Drive/GoodNotes/Merged File for Analysis/Complete_Agri_Climate.csv'
complete_agri_climate_df = pd.read_csv(file_path)
complete_agri_climate_df

,Year,State,Commodity,ACRES HARVESTED,"PRODUCTION, MEASURED IN $",YIELD,January-December Average Temperature (Units Degrees Fahrenheit),January-December Cooling Degree Days (Units Fahrenheit Degree-Days),January-December Heating Degree Days (Units Fahrenheit Degree-Days),January-December Maximum Temperature (Units Degrees Fahrenheit),...,Qv2M,Rh2M,T2Mdew,T2Mwet,Toa_Sw_Dwn,Ts,Wd10M,Wd2M,Ws10M,Ws2M
0,1981,alabama,WHEAT,565000,24860000,44,62,1793,3126,74,...,9,71,10,13,NaN,16,272,248,2,0
1,1981,alabama,POTATOES,13100,22859000,159,62,1793,3126,74,...,9,71,10,13,NaN,16,272,248,2,0
2,1981,alabama,CORN,530000,78705000,55,62,1793,3126,74,...,9,71,10,13,NaN,16,272,248,2,0
3,1981,alabama,COTTON,372000,113231000,545,62,1793,3126,74,...,9,71,10,13,NaN,16,272,248,2,0
4,1981,arizona,WHEAT,258000,21844000,85,61,2987,1782,75,...,5,51,-0,5,NaN,11,215,226,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6434,2022,iowa,CORN,12350000,16351400000,200,48,902,7209,59,...,7,71,3,6,27,9,264,268,5,4
6435,2022,louisiana,CORN,435000,492507000,170,67,2790,1686,78,...,11,76,14,17,31,19,162,159,2,0
6436,2022,louisiana,RICE,412000,466701000,6660,67,2790,1686,78,...,11,76,14,17,31,19,162,159,2,0
6437,2022,louisiana,COTTON,190000,158952000,904,67,2790,1686,78,...,11,76,14,17,31,19,162,159,2,0
6438,2022,west virginia,CORN,30000,34776000,168,52,815,5190,64,...,8,77,7,9,29,11,224,228,2,0

In [56]:
# Standardize the state names to be all lowercase in both dataframes
eco_socie_df['State'] = eco_socie_df['State'].str.lower()
complete_agri_climate_df['State'] = complete_agri_climate_df['State'].str.lower()

# Merge the eco_socie_df with the new dataframe on 'State' and 'Year' columns
merged_agri_climate_eco_df = pd.merge(eco_socie_df, complete_agri_climate_df, on=['State', 'Year'], how='inner')
merged_agri_climate_eco_df = merged_agri_climate_eco_df.drop(columns=['FIPS Code'])

merged_agri_climate_eco_df

,State,Year,GDP (Millions of dollars),Population (Number of persons),Personal Income (Dollars),Total Civilian Non-Institutional Population in State/Area,Total Civilian Labor Force in State/Area,Percent (%) of State/Area's Population,Total Employment in State/Area,Percent (%) of Labor Force Employed in State/Area,...,Qv2M,Rh2M,T2Mdew,T2Mwet,Toa_Sw_Dwn,Ts,Wd10M,Wd2M,Ws10M,Ws2M
0,alabama,1988,55527,4023842,13800,3057500,1874603,61,1738008,57,...,9,76,11,14,31,16,198,204,2,0
1,alabama,1988,55527,4023842,13800,3057500,1874603,61,1738008,57,...,9,76,11,14,31,16,198,204,2,0
2,alabama,1988,55527,4023842,13800,3057500,1874603,61,1738008,57,...,9,76,11,14,31,16,198,204,2,0
3,alabama,1988,55527,4023842,13800,3057500,1874603,61,1738008,57,...,9,76,11,14,31,16,198,204,2,0
4,alabama,2010,162069,4787998,33849,3690247,2196694,60,1968757,53,...,10,75,11,14,31,16,284,280,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6434,wyoming,2016,31090,581983,53421,450992,300464,67,284450,63,...,4,55,-2,3,27,8,243,246,4,3
6435,wyoming,2016,31090,581983,53421,450992,300464,67,284450,63,...,4,55,-2,3,27,8,243,246,4,3
6436,wyoming,2014,32680,580949,56252,449700,302865,67,289699,64,...,4,58,-2,2,27,7,259,262,4,3
6437,wyoming,2014,32680,580949,56252,449700,302865,67,289699,64,...,4,58,-2,2,27,7,259,262,4,3
6438,wyoming,2014,32680,580949,56252,449700,302865,67,289699,64,...,4,58,-2,2,27,7,259,262,4,3

In [59]:
# Save the resulting dataframe to a CSV file
final_file_path = '/content/drive/My Drive/GoodNotes/Merged File for Analysis/Merged_Agri_Climate_Eco_Data.csv'
merged_agri_climate_eco_df.to_csv(final_file_path, index=False)


print(f"Final merged dataframe saved to {final_file_path}")

Final merged dataframe saved to /content/drive/My Drive/GoodNotes/Merged File for Analysis/Merged_Agri_Climate_Eco_Data.csv